{{- with .Values.rpcSaas.clustersecretstore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .name }} 
spec:
  provider:
    gcpsm: # gcpsm provider
      projectID: {{ .projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .clusterLocation }}
          clusterName: {{ .clusterName }}
          serviceAccountRef:
            name: {{ .serviceAccountname }}
            namespace: {{ .serviceAccountnamespace }}
{{- end }}
