{{- if and .Values.secretManager.enabled .Values.secretManager.pvc.create -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{ if .Values.secretManager.pvc.name }}
  name: {{ .Values.secretManager.pvc.name }}
  {{ else }}
  name: {{ include "zenrock-mpc.fullname" . }}-secrets
  {{ end }}
  labels: 
    {{- include "zenrock-mpc.labels" . | nindent 4 }}
  {{- if .Values.secretManager.pvc.annotations }}
  {{- with .Values.secretManager.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- if .Values.secretManager.pvc.storageClassName }}
  storageClassName:
    {{ .Values.secretManager.pvc.storageClassName }}
  {{- end }}
  accessModes:
  {{- if not (empty .Values.secretManager.pvc.accessModes) }}
  {{- range .Values.secretManager.pvc.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.secretManager.pvc.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.secretManager.pvc.size | quote }}
{{- end -}}