{{- if .Values.service.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "zenrock-mpc.fullname" . }}
  labels:
    {{- include "zenrock-mpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "zenrock-mpc.selectorLabels" . | nindent 4 }}
{{- end }}