apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejector.fullname" . }}
  labels:
    {{- include "ejector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ejector.httpPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ejector.selectorLabels" . | nindent 4 }}
