---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-nethermind
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.nethermind.service.type }}
{{- if .Values.global.svcHeadless }}
  clusterIP: None
{{- end }}
{{- if .Values.global.sessionAffinity.enabled }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.global.sessionAffinity.timeoutSeconds }}
{{- end }}
  ports:
  {{- if .Values.nethermind.jsonrpc.enabled }}
    - port: {{ .Values.nethermind.jsonrpc.ports.rest }}
      targetPort: json-rest-neth
      protocol: TCP
      name: json-rest-neth
    - port: {{ .Values.nethermind.jsonrpc.ports.websocket }}
      targetPort: json-ws-neth
      protocol: TCP
      name: json-ws-neth
  {{- end }}
  {{- if .Values.global.JWTSecret }}
    - port: {{ .Values.nethermind.jsonrpc.engine.port }}
      targetPort: engine
      protocol: TCP
      name: engine
  {{- end }}
  {{- if .Values.global.metrics.enabled }}
    - port: {{ .Values.nethermind.metrics.port }}
      targetPort: metrics-neth
      protocol: TCP
      name: metrics-neth
  {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
