apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.main.network }}-jwt
spec:
  refreshInterval: {{ .Values.global.secretStore.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.global.main.env }}-gcp-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.main.network }}-jwt
    creationPolicy: Owner
  data:
  - remoteRef:
      key: {{ .Values.global.secretStore.remoteRef.key }}
      property: {{ .Values.global.secretStore.remoteRef.property }}
      version: "{{ .Values.global.secretStore.remoteRef.version }}"
    secretKey: jwt.hex