apiVersion: v2
name: mev-boost
description: mev-boost allows proof-of-stake Ethereum consensus clients to outsource block construction
version: 1.0.2
home: https://boost.flashbots.net/
keywords:
  - ethereum
  - blockchain
  - mev-boost
type: application
appVersion: "1.7.1"
maintainers:
  - name: matilote
  - name: aivarasko
dependencies:
  - name: common
    repository: file://../common
    version: 1.0.1
