---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ssv-node.fullname" . }}-p2p"
  labels:
    {{- include "ssv-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.ports.p2pTCP }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ .Values.service.ports.p2pUDP }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
  selector:
    {{- include "ssv-node.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ssv-node.fullname" . }}"
  labels:
    {{- include "ssv-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ssv-node.selectorLabels" . | nindent 4 }}
