{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ssv-node.fullname" . }}
  labels:
    {{- include "ssv-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ssv-node.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
{{- end }}
