apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ssv-node.fullname" . }}
  labels:
    {{- include "ssv-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ssv-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssv-node.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssv-node.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: p2p-tcp
              containerPort: {{ .Values.service.ports.p2pTCP }}
              protocol: TCP
            - name: p2p-udp
              containerPort: {{ .Values.service.ports.p2pUDP }}
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.service.ports.metrics }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env: {{- toYaml .Values.env_vars | nindent 12 }}
          command:
            - /bin/sh
            - -c
          args: {{ .Values.config.args | toYaml | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.externalSecrets.enabled }}
            - name: secrets
              mountPath: "/etc/ssv-node"
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ssv-node.fullname" . }}
        {{- if .Values.externalSecrets.enabled }}
        - name: secrets
          secret:
            secretName: {{ include "ssv-node.fullname" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
