{{- if $.Values.svc.ingress.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ .Values.deployment.projectName }}-wss
  namespace: {{ .Values.deployment.namespace }}
spec:
{{ toYaml .Values.svc.wss.backendConfig | indent 2 }}
{{- end -}}