{{- with .Values.feederGateway.clustersecretstore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ $.Values.feederGateway.secret.secretStoreName }} # Using the value from .Values.feederGateway.secret.secretStoreName
spec:
  provider:
    gcpsm: # gcpsm provider
      projectID: {{ .projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .clusterLocation }}
          clusterName: {{ .clusterName }}
          serviceAccountRef:
            name: {{ .serviceAccountname }}
            namespace: {{ .serviceAccountnamespace }}
{{- end }}
