{{- if $.Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.projectName }}
  namespace: {{ .Values.deployment.namespace }}
data:
  {{- range $key, $value := .Values.config }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end -}}
