{{- if .Values.secret }}
{{- with .Values.secret.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.deployment.projectName }}
  namespace: {{ $.Values.deployment.namespace }}
spec:
  refreshInterval: {{ $.Values.secret.data.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secret.data.secretStoreName }}
    kind: {{ $.Values.secret.data.secretStoreKind }}
  target:
    name: {{ $.Values.secret.data.targetName }}
    creationPolicy: {{ $.Values.secret.data.targetCreationPolicy }}
  dataFrom:
    - extract:
        key: {{ $.Values.secret.data.dataFromKey }} # name of the secret in secret manager (GCP secret manager)
{{- end }}
{{- end }}
