{{- if .Values.secret }}
{{- with .Values.secret.feederGateway }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.deployment.projectName }}
  namespace: {{ $.Values.deployment.namespace }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreName }}
    kind: {{ .secretStoreKind }}
  target:
    name: {{ .targetName }}
    creationPolicy: {{ .targetCreationPolicy }}
  data:
    - remoteRef:
        key: {{ .key }}
        property: {{ .property }}
        version: "{{ .version }}"
      secretKey: {{ .secretKey }}
{{- end }}
{{- end }}