{{- if .Values.secret }}
{{- with .Values.secret.data }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.deployment.projectName }}
  namespace: {{ $.Values.deployment.namespace }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreName }}
    kind: {{ .secretStoreKind }}
  target:
    name: {{ .targetName }}
    creationPolicy: {{ .targetCreationPolicy }}
  dataFrom:
    - extract:
        key: {{ .dataFromKey }} # name of the secret in secret manager (GCP secret manager)
{{- end }}
{{- end }}