{{- if $.Values.svc_lb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.projectName }}-wss-internal-lb
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.projectName }}
  annotations:
    cloud.google.com/backend-config:  '{"ports": {"{{ $.Values.svc.wss.port }}":"{{ .Values.deployment.projectName }}-wss"}}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: internal
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.svc_lb.wss_hostname }}
spec:
  type: {{ .Values.svc_lb.clustertype }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 30
  ports:
  - port: {{ .Values.svc.wss.port }}
    name: port-{{ .Values.svc.wss.port }}
    targetPort: {{ .Values.svc.wss.port }}
    protocol: TCP
  selector:
    app: {{ .Values.deployment.projectName }}
{{- end -}}
