apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.projectName }}-wss
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.projectName }}
  annotations:
    cloud.google.com/backend-config:  '{"ports": {"{{ $.Values.svc.wss.port }}":"{{ .Values.deployment.projectName }}-wss"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.svc.wss.clustertype }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 30
  ports:
  - port: {{ .Values.svc.wss.port }}
    name: port-{{ .Values.svc.wss.port }}
    targetPort: {{ .Values.svc.wss.port }}
    protocol: TCP
  selector:
    app: {{ .Values.deployment.projectName }}