{{- if .Values.provisioningExternalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ template "validators.fullname" . }}
  labels:
    {{- include "validators.labels" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.provisioningExternalSecrets.secretStoreRef.name }}
    kind: {{ .Values.provisioningExternalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ template "validators.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: provisioning-web3signer-{{ template "validators.onwership" . }}-web3signer-eso
        property: dbKeystoreUrl
{{- end }}
