---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  vouch.yaml: |
    {{- toYaml .Values.vouchFullConfig | nindent 4 }}
  vouch-fallback.yaml: |
  {{- if .Values.vouchFallbackFullConfig }}
    {{- toYaml .Values.vouchFallbackFullConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.vouchFallbackConfigAddition }}
    {{- toYaml .Values.vouchFullConfig | nindent 4 }}
    {{- toYaml .Values.vouchFallbackConfigAddition | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{ $root := . }}
{{- range $path, $_ :=  .Files.Glob  "scripts/**.sh" }}
{{- with $root }}
  {{ $path | replace "scripts/" ""}}: |-
{{ .Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
