---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  vouch.yaml: |
    beacon-node-address: {{ .Values.vouch.beaconnodeaddress }}
    beacon-node-addresses: {{ .Values.vouch.beaconnodeaddresses }}
    log-level: {{ .Values.vouch.loglevel }}
    graffiti:
      static:
        value: {{ .Values.vouch.graffiti.static.value }}
    accountmanager:
      dirk:
        endpoints: {{ .Values.vouch.accountmanager.dirk.endpoints }}
        client-cert: {{ .Values.vouch.accountmanager.dirk.clientcert }}
        client-key: {{ .Values.vouch.accountmanager.dirk.clientkey }}
        ca-cert: {{ .Values.vouch.accountmanager.dirk.cacert }}
        accounts: {{ .Values.vouch.accountmanager.dirk.accounts }}
        timeout: {{ .Values.vouch.accountmanager.dirk.timeout }}
    feerecipient:
      default-address: {{ .Values.vouch.feerecipient.defaultaddress }}
    metrics:
      prometheus:
        log-level: {{ .Values.vouch.metrics.prometheus.loglevel }}
        listen-address: {{ .Values.vouch.metrics.prometheus.listenaddress }}
    blockrelay:
      fallback-fee-recipient: {{ .Values.vouch.blockrelay.fallbackfeerecipient }}