{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dlcbtc.name" . }}
  namespace:  {{ template "dlcbtc.namespace" . }}
  labels:
    {{- include "dlcbtc.matchLabels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
