apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.global.main.env }}-gcp-store
spec:
  provider:
    gcpsm: # gcpsm provider
      projectID: {{ .Values.global.secretStore.gcp.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.global.secretStore.gcp.clusterLocation }}
          clusterName: {{ .Values.global.secretStore.gcp.clusterName }}
          serviceAccountRef:
            name: {{ .Values.global.secretStore.gcp.serviceAccountRef.name }}
            namespace: {{ .Values.global.secretStore.gcp.serviceAccountRef.namespace }}
