apiVersion: v2
description: The Cloud-Native Ingress and API-management
maintainers:
  - name: anishgehlot
    email: anish@nethermind.io
name: kong
sources:
  - https://github.com/Kong/charts/tree/main/charts/kong
version: 2.33.4
appVersion: "3.5"
dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
