apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ template "validators.fullname" . }}
  labels:
    {{- include "validators.labels" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef }}
    kind: SecretStore
  target:
    name: eso-{{ template "validators.fullname" . }}
    creationPolicy: Owner
  data:
    {{- .Values.externalSecrets.data | toYaml | trim | nindent 2 }}