{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ template "validators.fullname" . }}
  labels:
    {{- include "validators.labels" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ template "validators.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: {{ .Values.global.label }}-external-secrets
        property: dbKeystoreUrl
    {{- .Values.externalSecrets.data | toYaml | trim | nindent 2 }}
{{- end }}