{{- if .Values.enabled }}
{{- $root := . -}}
{{- $counter := 0 }}
{{- $step := .Values.validatorsIndexStart }}
{{- range (untilStep (int .Values.validatorsIndexStart ) (int .Values.validatorsIndexEnd) 1) }}
  {{- $step = int (add1 $step) }}
{{- end }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "validators.fullname" $root }}-validator{{$step}}
  labels:
    {{- include "validator.labels" $root | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "validators.selectorLabels" $root | nindent 6 }}
  serviceName: {{ template "validators.fullname" $root }}
  template:
    metadata:
      labels:
        {{- include "validators.selectorLabels" $root | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum }}
    spec:
    {{- with $root.Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
    {{- end }}
    {{- with $root.Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with $root.Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with $root.Values.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
      serviceAccountName: "validator{{$step}}"
      priorityClassName: {{ $root.Values.priorityClassName | quote }}
      initContainers:
        - name: init-validator
          image: "{{ $root.Values.initImage.repository }}:{{ $root.Values.initImage.tag }}"
          imagePullPolicy: {{ $root.Values.initImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          env:
            - name: VAULT_ADDR
              value: {{ $root.Values.vault.endpoint | quote }}
            - name: NETWORK_ID
              value: {{ $root.Values.network | quote }}
            - name: VALIDATORS_MOUNT_PATH
              value: {{ $root.Values.vault.validatorsMountPath | quote }}
            - name: KUBERNETES_AUTH_NAME
              value: {{ $root.Values.vault.kubernetesAuthName | quote }}
            - name: SERVICE_ACCOUNT
              value: "validator{{$step}}"
            - name: REIMPORT
              value: {{ $root.Values.reimportKeystores | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: configs
              mountPath: "/mnt/configs"
            - name: validator-init
              mountPath: /data/scripts
      {{- if $.Values.persistence.enabled }}
        {{- include "init-validator-info" $root | nindent 8 }}
      {{- end }}
      {{- if and $.Values.persistence.enabled $.Values.initChownData }}
        {{- include "init-chown" $root | nindent 8 }}
      {{- end }}
      containers:
        - name: validator
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          args:
            - "validator-client"
            - "--validator-keys=/data/teku/validator/keys:/data/teku/validator/passwords"
            - "--log-destination=CONSOLE"
            - "--data-base-path=/data/teku"
          {{- if $root.Values.merge.enabled }}
            - "--validators-proposer-default-fee-recipient={{ $root.Values.merge.feeRecipient }}"
          {{- if $root.Values.mevBoost.enabled }}
            - "--validators-proposer-blinded-blocks-enabled=true"
            - "--validators-builder-registration-default-enabled=true"
          {{- end }}
          {{- end }}
          {{- range $root.Values.extraFlags }}
            - {{ . | quote }}
          {{- end }}
            - "--beacon-node-api-endpoints={{ $root.Values.beaconChainRpcEndpoints | join "," }}"
            - "--validators-graffiti={{ $.Values.graffiti }}"
          {{- if $root.Values.metrics.enabled }}
            {{- range $root.Values.metrics.flags }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
        {{- if $root.Values.metrics.enabled }}
          ports:
            - containerPort: {{ $root.Values.metrics.port }}
              name: metrics
              protocol: TCP
        {{- end }}
        {{- with $root.Values.resources }}
          resources:
            {{ toYaml . | nindent 16 | trim }}
        {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: configs
              mountPath: "/mnt/configs"
        {{- with ($root.Values.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with ($root.Values.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: configs
          configMap:
            name: {{ template "validators.fullname" $root }}-configs
        - name: validator-init
          configMap:
            name: {{ template "validators.fullname" $root }}-init
{{- if (not $root.Values.persistence.enabled) }}
        - name: data
          emptyDir: {}
{{- else }}
        - name: data
          persistentVolumeClaim:
            claimName: data-validator{{$step}}
{{- end }}
{{- end }}
