{{- if and (eq .Values.network "gnosis") (eq .Values.type "teku") }}
{{- fail "Gnosis chain network can't be used with teku client" }}
{{- end }}

{{- if and (not .Values.beaconChainRpcEndpoints) (not .Values.beaconChainRpcEndpointsRandomized) }}
{{- fail ".Values.beaconChainRpcEndpoints is empty" }}
{{- end }}

{{- if not .Values.vault.endpoint }}
{{- fail ".Values.vault.endpoint is empty" }}
{{- end }}
