apiVersion: v1
kind: Service
metadata:
  name: {{ include "posmoni.fullname" . }}
  labels:
    {{- include "posmoni.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "posmoni.selectorLabels" . | nindent 4 }}
