### Basic
deployment:
   projectName: goerli
   namespace: dev-goerli-1
   replicas: 1
   imagename: nethermind/juno
   imagetag: v0.6.0
   snapshotUrl: "https://juno-snapshot.s3.us-east-2.amazonaws.com/goerli2/juno_goerli2_v0.4.0_125026.tar" # if Value is Null sync start from 0 block
   resources:
    limits:
      cpu: "4"
      memory: 14Gi
    requests:
      cpu: "2"
      memory: 8Gi
   port:
    - 6060

### Container Arguments
args:
   --http-port: "6060"
   --db-path: "/var/lib/juno"
   --network: "goerli"
   --http: "true"
   --metrics: "true"
### Node selector and Tanits
nodeSelector:
   enabled: false
   label:
     network: juno

taintsToleration:
   enabled: false
   tolerations:
      network: juno

### Service account
serviceAccount: 
   enabled: false
   name: "juno"

### Networking Service
svc:
   clustertype: ClusterIP     # Support: LoadBalancer, NodePort, ClusterIP
   fdqn: juno.cluster.local
   targetPort: "6060"
# Ingress
   ingress:
    enabled: true
    ## GCP Certificate
    managedCertificate:
      enabled: false
      domain:
        - "rpc-goerli-1-juno.nethermind.dev"
    host: "rpc-goerli-1-juno.nethermind.dev"   
    ## ALB Backend Config
    backendConfig:
      sessionAffinity:
         affinityType: "CLIENT_IP"
      connectionDraining:
         drainingTimeoutSec: 30
      healthCheck:
         checkIntervalSec: 15
         timeoutSec: 15
         healthyThreshold: 1
         unhealthyThreshold: 2 
         port: 6060
         type: HTTP
         requestPath: /
      customResponseHeaders:
         headers:
          - "X-Frame-Options: SAMEORIGIN"
          - "X-Content-Type-Options: nosniff"
          - "X-XSS-Protection: 1; mode=block"
          - "Referrer-Policy: no-referrer-when-downgrade"
          - "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload"
    ## Ingress Rules
    rules:
    - host: "rpc-goerli-juno.nethermind.dev"
      http:
        paths:
         - path: /
           pathType: ImplementationSpecific
           backend:
            service:
             name: goerli
             port:
               number: 6060

### Horizontal pod scaling
hpa:
   enabled: false
   minReplicas: 1
   maxReplicas: 2
   cpuUtilization: 80

### Persistant Volume
pvc:
   enabled: true
   storageClassName: standard

   mount:
   - pvName: pv
     mountPath: /var/lib/juno
     storageSize: 250Gi

### Environment Variables 
env:
   enabled: false
   data:
   - name: NETWORK
     value: "juno"
