---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.statefulset" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  serviceName: {{ include "common.names.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        execution: {{ .Values.execution.client }}
        beacon: {{ .Values.beacon.client }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with (concat .Values.global.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.global.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.global.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- if .Values.global.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.global.terminationGracePeriodSeconds }}
    {{- end }}
      serviceAccountName: {{ include "common.names.fullname" . }}
      priorityClassName: {{ .Values.global.priorityClassName | quote }}
      initContainers:
        {{/*
        Container used for initialising data directory and setting right values for ports and external_ip
        */}}
        - name: init
          image: "{{ .Values.global.initImage.repository }}:{{ .Values.global.initImage.tag }}"
          imagePullPolicy: {{ .Values.global.initImage.pullPolicy }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ['/bin/sh', '/scripts/init.sh']
          volumeMounts:
          {{- if .Values.global.sharedPersistence.enabled }}
            - name: data
              mountPath: /data
          {{- else }}
            - name: data-execution
              mountPath: /data/execution
            - name: data-beacon
              mountPath: /data/beacon
          {{- end }}
            - name: env-nodeport
              mountPath: /env
            - name: scripts-init
              mountPath: /scripts
        {{/*
        Container used for initialising nimbus checkpoint sync
        */}}
        {{- if and (eq .Values.beacon.client "nimbus") .Values.beacon.checkPointSync.enabled }}
        - name: init-nimbus
          image: "{{ (pluck .Values.beacon.client .Values.global.image.beacon | first ).repository }}:{{ (pluck .Values.beacon.client .Values.global.image.beacon | first ).tag }}"
          imagePullPolicy: {{ .Values.beacon.imagePullPolicy }}
          command:
            - sh
            - -ac
            - >
              exec /home/user/nimbus-eth2/build/nimbus_beacon_node
              trustedNodeSync
              --backfill=false 
              --network={{ .Values.global.network }}
              --data-dir=/data/beacon
              --trusted-node-url={{ .Values.beacon.checkPointSync.url }}
          volumeMounts:
          {{- if .Values.global.sharedPersistence.enabled }}
            - name: data
              mountPath: /data
          {{- else }}
            - name: data-beacon
              mountPath: /data/beacon
          {{- end }}
        {{- end }}
      containers:
        {{/*
        Container used for Execution clients: Nethermind, Geth, Besu, Erigon
        */}}
        - name: execution
          image: "{{ (pluck .Values.execution.client .Values.global.image.execution | first ).repository }}:{{ (pluck .Values.execution.client .Values.global.image.execution | first ).tag }}"
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          {{- if .Values.global.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          {{- end }}
          command:
            - sh
            - -ac
            - >
              sleep 36000
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if .Values.execution.javaOpts.enabled }}
            - name: BESU_OPTS
              value: {{ .Values.execution.javaOpts.maxHeapSize }}
          {{- end }}
          {{- if .Values.global.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" . }}
          {{- end }}
          ports:
            {{- if eq .Values.execution.client "erigon" }}
            - name: grpc-exec
              protocol: TCP
              containerPort: {{ .Values.execution.jsonrpc.grpc.port }}
            {{- end }}
            {{- if .Values.execution.jsonrpc.enabled }}
            - name: engine-exec
              containerPort: {{ .Values.execution.jsonrpc.engine.port }}
            - name: jsonrpc-exec
              containerPort: {{ .Values.execution.jsonrpc.http.port }}
            {{- if .Values.execution.jsonrpc.websocket.enabled }}
            - name: ws-exec
              containerPort: {{ .Values.execution.jsonrpc.websocket.port }}
            {{- end }}
            {{- end }}
            {{- if and .Values.global.metrics.enabled .Values.execution.metrics.enabled }}
            - name: metrics-exec
              containerPort: {{ .Values.execution.metrics.port }}
            {{- end }}
            {{- if .Values.global.p2pNodePort.enabled }}
            - name: p2p-tcp-exec
              containerPort: {{ include "execution.p2pPort" . }}
              protocol: TCP
            - name: p2p-udp-exec
              containerPort: {{ include "execution.p2pPort" . }}
              protocol: UDP
            {{- end }}
          volumeMounts:
          {{- if .Values.global.sharedPersistence.enabled }}
            - name: data
              mountPath: /data
          {{- else }}
            - name: data-execution
              mountPath: /data/execution
          {{- end }}
            {{- if .Values.global.externalSecrets.enabled }}
            - name: external-secrets
              mountPath: /external-secrets
              readOnly: true
            {{- end }}
            {{- if .Values.global.JWTSecret }}
            - name: jwtsecret
              mountPath: /secret
              readOnly: true
            {{- end }}
            - name: env-nodeport
              mountPath: /env
          {{- with .Values.execution.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
          {{- end }}
        {{/*
        Container used for Beacon clients: Prysm, Teku, Lighthouse, Nimbus, Lodestar
        */}}
        - name: beacon
          image: "{{ (pluck .Values.beacon.client .Values.global.image.beacon | first ).repository }}:{{ (pluck .Values.beacon.client .Values.global.image.beacon | first ).tag }}"
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          {{/*
          Configuration for Prysm beacon client
          */}}
          command:
            - sh
            - -ac
            - >
              sleep 36000
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if and (eq .Values.beacon.client "teku") .Values.beacon.javaOpts.enabled }}
            - name: JAVA_OPTS
              value: {{ .Values.beacon.javaOpts.maxHeapSize }}
          {{- end }}
          ports:
          {{- if and (eq .Values.beacon.client "prysm") .Values.beacon.grpc.enabled }}
            - containerPort: {{ .Values.beacon.grpc.port }}
              name: {{ .Values.beacon.grpc.portName }}-beacon
              protocol: TCP
          {{- end }}
          {{- if .Values.global.p2pNodePort.enabled }}
            - name: p2p-tcp-beacon
              containerPort: {{ include "beacon.p2pPort" . }}
              protocol: TCP
            - name: p2p-udp-beacon
              containerPort: {{ include "beacon.p2pPort" . }}
              protocol: UDP
          {{- end }}
          {{- if .Values.beacon.restApi.enabled }}
            - containerPort: {{ index .Values.beacon.restApi.portMap .Values.beacon.client }}
              name: http-beacon
              protocol: TCP
          {{- end }}
          {{- if and .Values.global.metrics.enabled .Values.beacon.metrics.enabled }}
            - containerPort: {{ .Values.beacon.metrics.port }}
              name: metrics-beacon
              protocol: TCP
          {{- end }}
          volumeMounts:
          {{- if .Values.global.sharedPersistence.enabled }}
            - name: data
              mountPath: /data
          {{- else }}
            - name: data-beacon
              mountPath: /data/beacon
          {{- end }}
          {{- if .Values.global.externalSecrets.enabled }}
            - name: external-secrets
              mountPath: /external-secrets
              readOnly: true
          {{- end }}
          {{- if .Values.global.JWTSecret }}
            - name: jwtsecret
              mountPath: /secret
              readOnly: true
          {{- end }}
            - name: env-nodeport
              mountPath: /env
        {{- with .Values.beacon.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
        {{- end }}
        {{- if and .Values.global.ethsider.enabled .Values.beacon.restApi.enabled .Values.execution.jsonrpc.enabled }}
        - name: ethsider
          image: "{{ .Values.global.ethsider.repository }}:{{ .Values.global.ethsider.tag }}"
          imagePullPolicy: {{ .Values.global.ethsider.pullPolicy }}
          env:
            - name: EXECUTION_ENDPOINT
              value: "http://localhost:{{ .Values.execution.jsonrpc.http.port }}"
            - name: BEACON_ENDPOINT
              value: "http://localhost:{{ index .Values.beacon.restApi.portMap .Values.beacon.client }}"
            - name: BIND_ADDR
              value: "{{ .Values.global.ethsider.bindAddr }}"
          ports:
            - containerPort: {{ .Values.global.ethsider.bindAddr }}
              name: sidecar
              protocol: TCP
        {{- if .Values.global.ethsider.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.global.ethsider.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.global.ethsider.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.global.ethsider.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.global.ethsider.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.global.ethsider.livenessProbe.successThreshold }}
            httpGet:
              path: {{ .Values.global.ethsider.livenessProbe.httpGet.path }}
              port: {{ .Values.global.ethsider.livenessProbe.httpGet.port }}
              scheme: {{ .Values.global.ethsider.livenessProbe.httpGet.scheme }}
        {{- end }}
        {{- if .Values.global.ethsider.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.global.ethsider.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.global.ethsider.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.global.ethsider.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.global.ethsider.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.global.ethsider.readinessProbe.successThreshold }}
            httpGet:
              path: {{ .Values.global.ethsider.readinessProbe.httpGet.path }}
              port: {{ .Values.global.ethsider.readinessProbe.httpGet.port }}
              scheme: {{ .Values.global.ethsider.readinessProbe.httpGet.scheme }}
        {{- end }}
      {{- end }}
      volumes:
        - name: scripts-init
          configMap:
            name: {{ include "common.names.fullname" . }}-init
      {{- if .Values.global.JWTSecret }}
        - name: jwtsecret
          secret:
            secretName: {{ include "common.names.fullname" . }}
      {{- end }}
      {{- if .Values.global.externalSecrets.enabled }}
        - name: external-secrets
          secret:
            secretName: eso-{{ include "common.names.fullname" . }}
      {{- end }}
        - name: env-nodeport
          emptyDir: {}
  volumeClaimTemplates:
    {{- if .Values.global.sharedPersistence.enabled }}
    - metadata:
        name: data
        labels:
          {{- include "common.labels.statefulset" . | nindent 10 }}
      {{- with .Values.global.sharedPersistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        accessModes: {{ .Values.global.sharedPersistence.accessModes }}
        storageClassName: {{ .Values.global.sharedPersistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.global.sharedPersistence.size | quote }}
    {{- else }}
    - metadata:
        name: data-execution
        labels:
          {{- include "common.labels.statefulset" . | nindent 10 }}
      {{- with .Values.execution.persistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        accessModes: {{ .Values.execution.persistence.accessModes }}
        storageClassName: {{ .Values.execution.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.execution.persistence.size | quote }}
    - metadata:
        name: data-beacon
        labels:
          {{- include "common.labels.statefulset" . | nindent 10 }}
      {{- with .Values.beacon.persistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        accessModes: {{ .Values.beacon.persistence.accessModes }}
        storageClassName: {{ .Values.beacon.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.beacon.persistence.size | quote }}
    {{- end }}
