apiVersion: v1
name: enode-collector
description: enode-collector fetches and serves a list of enodes which can be used to quicker bootstrapping of Ethereum nodes
version: 1.0.0
home: https://boost.flashbots.net/
keywords:
  - ethereum
  - blockchain
  - enode-collector
type: application
appVersion: "1.6.0"

dependencies:
- name: common
  repository: file://../common
  version: 1.0.0
