{{- if .Values.global.podDisruptionBudget.enabled }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
{{- if .Values.global.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.global.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.global.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.global.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
{{- end }}
