apiVersion: v2
name: validators
description: Ethereum validators chart
type: application
version: 0.0.1

keywords:
  - ethereum
  - blockchain
  - lighthouse
  - prysm
  - teku
  - nimbus
  - lodestar
  - validators