apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}     
spec:
  selector:
    app: {{ .Values.deployment.label }}   
  type: ClusterIP
  ports:
  - protocol: TCP   
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
