{{- if .Values.global.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "kapi.fullname" . }}
  labels:
    {{- include "kapi.labels" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.global.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.global.externalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ include "kapi.fullname" . }}
    creationPolicy: Owner
  data:
    {{- .Values.global.externalSecrets.data | toYaml | trim | nindent 2 }}
{{- end }}