apiVersion: v1
kind: Service
metadata:
  name: {{ include "kapi.fullname" . }}
  labels:
    {{- include "kapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.kapi.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kapi.selectorLabels" . | nindent 4 }}
