{{- if and .Values.deployment.kong.enabled (or .Values.proxy.multiClusterIngress.enabled) }}
{{- if and .Values.proxy.enabled (or .Values.proxy.http.enabled .Values.proxy.tls.enabled) -}}
{{- $serviceConfig := dict -}}
{{- $serviceConfig := merge $serviceConfig .Values.proxy -}}
{{- $_ := set $serviceConfig "fullName" (include "kong.fullname" .) -}}
{{- $_ := set $serviceConfig "namespace" (include "kong.namespace" .) -}}
{{- $_ := set $serviceConfig "metaLabels" (include "kong.metaLabels" .) -}}
{{- $_ := set $serviceConfig "selectorLabels" (include "kong.selectorLabels" .) -}}
{{- $_ := set $serviceConfig "serviceName" "proxy" -}}
{{- include "kong.mciservice" $serviceConfig }}
{{ if .Values.proxy.multiClusterIngress.enabled }}
---
{{ include "kong.multiClusterIngress" $serviceConfig }}
{{- end -}}
{{- end -}}
{{- end -}}