{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "validators.fullname" . }}
  labels:
    {{- include "validators.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "validators.fullname" . }}
subjects:
  {{- $root := . -}}
  {{- $step := .Values.validatorsIndexStart }}
  {{- range (untilStep (int .Values.validatorsIndexStart ) (int .Values.validatorsIndexEnd) 1) }}
    {{- $step = int (add1 $step) }}
  - kind: ServiceAccount
    name: validator{{$step}}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
{{- end }}
