{{- if .Values.serviceAccount.create -}}
{{- $root := . -}}
{{- $step := .Values.validatorsIndexStart }}
{{- range (untilStep (int .Values.validatorsIndexStart ) (int .Values.validatorsIndexEnd) 1) }}
  {{- $step = int (add1 $step) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: validator{{$step}}
  labels:
    {{- include "validators.labels" $root | nindent 4 }}
  {{- with $root.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}