{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add1 .Values.replicaCount)) 1) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $root }}-{{.}}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
data:
  dirk.yaml: |
    log-level: {{ $root.Values.dirk.loglevel }}
    server:
      id: {{.}}
      name: {{ include "dirk.fullname" $root }}-{{.}}-0.{{ include "dirk.fullname" $root }}
      listen-address: 0.0.0.0:{{ $root.Values.service.httpPort }}
    certificates:
      ca-cert: file:///data/dirk/dirk-{{.}}/certs/ca.crt
      server-cert: file:///data/dirk/dirk-{{.}}/certs/{{ include "dirk.fullname" $root }}-{{.}}-0.{{ include "dirk.fullname" $root }}.crt
      server-key: file:///data/dirk/dirk-{{.}}/certs/{{ include "dirk.fullname" $root }}-{{.}}-0.{{ include "dirk.fullname" $root }}.key
    storage-path: /data/dirk/dirk-{{.}}/storage
    stores:
    - name: Local
      type: filesystem
      location: /data/dirk/dirk-{{.}}/wallets
    peers:
      1: {{ include "dirk.fullname" $root }}-1-0.{{ include "dirk.fullname" $root }}:{{ $root.Values.service.httpPort }}
      2: {{ include "dirk.fullname" $root }}-2-0.{{ include "dirk.fullname" $root }}:{{ $root.Values.service.httpPort }}
      3: {{ include "dirk.fullname" $root }}-3-0.{{ include "dirk.fullname" $root }}:{{ $root.Values.service.httpPort }}
    unlocker:
      account-passphrases:
        - secret
    permissions:
      client1:
        Validators: All
    metrics:
      listen-address: 0.0.0.0:{{ $root.Values.metricsPort }}
    tracing:
      address: {{ $root.Values.dirk.tracing.address | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-scripts
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{ $root := . }}
{{- range $path, $_ :=  .Files.Glob  "scripts/**.sh" }}
{{- with $root }}
  {{ $path | replace "scripts/" ""}}: |-
{{ .Files.Get $path | indent 4 }}
{{- end }}
{{- end }}