{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add1 .Values.replicaCount)) 1) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $root }}-{{.}}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
data:
  dirk.yaml: |
    log-level: Debug
    server:
      id: {{.}}
      name: {{ include "dirk.fullname" $root }}-{{.}}
      listen-address: 0.0.0.0:{{ $root.Values.service.httpPort }}
    certificates:
      ca-cert: file:///data/dirk/dirk-{{.}}/certs/ca.crt
      server-cert: file:///data/dirk/dirk-{{.}}/certs/dirk-{{.}}.crt
      server-key: file:///data/dirk/dirk-{{.}}/certs/dirk-{{.}}.key
    storage-path: /data/dirk/dirk-{{.}}/storage
    stores:
    - name: Local
      type: filesystem
      location: /data/dirk/dirk-{{.}}/wallets
    peers:
      1: {{ include "dirk.fullname" $root }}-1:{{ $root.Values.service.httpPort }}
      2: {{ include "dirk.fullname" $root }}-2:{{ $root.Values.service.httpPort }}
      3: {{ include "dirk.fullname" $root }}-3:{{ $root.Values.service.httpPort }}
    unlocker:
      account-passphrases:
        - secret
    process:
      generation-passphrase: secret
    permissions:
      client1:
        Validators: All
{{- end }}