{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add1 .Values.replicaCount)) 1) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $root }}-{{.}}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
data:
  config.yaml: |
    log-level: Debug
    server:
      id: {{.}}
      name: dirk-{{.}}
      listen-address: 0.0.0.0:{{ $root.Values.service.httpPort }}
    certificates:
      ca-cert: file:///root/.dirk/security/ca.crt
      server-cert: file:///root/.dirk/security/dirk-{{.}}.crt
      server-key: file:///root/.dirk/security/dirk-{{.}}.key
    storage-path: /root/.dirk/storage
    stores:
    - name: Local
      type: filesystem
      location: /root/.dirk/wallets
    peers:
      1: dirk-1:{{ $root.Values.service.httpPort }}
      2: dirk-2:{{ $root.Values.service.httpPort }}
      3: dirk-3:{{ $root.Values.service.httpPort }}
    unlocker:
      account-passphrases:
        - secret
    process:
      generation-passphrase: secret
    permissions:
      client1:
        Validators: All

{{- end }}