{{- if .Values.provisioningExternalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.provisioningExternalSecrets.secretStoreRef.name }}
    kind: {{ .Values.provisioningExternalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ include "common.names.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: ESO_DECRYPTION_KEY
      remoteRef:
        key: provisioning-{{ include "common.names.fullname" . }}
        property: decryptionKey
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: provisioning-{{ include "common.names.fullname" . }}
        property: dbKeystoreUrl
{{- end }}
