{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add1 .Values.replicaCount)) 1) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dirk.fullname" . }}-{{.}}
  labels:
    {{- include "dirk.labels" . | nindent 4 }}
  annotations:
    prometheus.io/probe: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dirk.selectorLabels" . | nindent 4 }}
{{- end }}