{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add .Values.replicaCount 2)) 1) }}


apiVersion: {{ include "common.capabilities.statefulset.apiVersion" $root }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" $root }}-{{.}}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $root | nindent 6 }}
  serviceName: {{ include "common.names.fullname" $root }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" $root | nindent 8 }}
    spec:
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dirk.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: "{{ $root.Values.initImage.repository }}:{{ $root.Values.initImage.tag }}"
          imagePullPolicy: {{ $root.Values.initImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -ac
            - >
              mkdir -p /data/dirk /data/keystore;
              chown -R {{ $root.Values.podSecurityContext.runAsUser }}:{{ $root.Values.podSecurityContext.fsGroup }} /data/dirk
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          volumeMounts:
            - name: data
              mountPath: /data
        - name: fetch-keys
          image: "{{ $root.Values.cliImage.repository }}:{{ $root.Values.cliImage.tag }}"
          imagePullPolicy: {{ $root.Values.cliImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          args: ["sync-dirk-keys", "--db-url", $(ESO_DB_KEYSTORE_URL), "--wallet-dir", "/data/dirk", "--decryption-key-env", "ESO_DECRYPTION_KEY"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: sleeper
          image: "bash:latest"
          imagePullPolicy: {{ $root.Values.cliImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          command: [ "/usr/local/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" $root }}
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi

{{- end }}