{{- $root := . -}}
{{- $counter := 0 }}
{{- range (untilStep 1 (int (add1 .Values.replicaCount)) 1) }}

---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" $root }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" $root }}-{{.}}
  labels:
    {{- include "common.labels.standard" $root | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $root | nindent 6 }}
  serviceName: {{ include "common.names.fullname" $root }}
  template:
    metadata:
      {{- with $root.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.labels.matchLabels" $root | nindent 8 }}
    spec:
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dirk.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: "{{ $root.Values.initImage.repository }}:{{ $root.Values.initImage.tag }}"
          imagePullPolicy: {{ $root.Values.initImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          command:
            - bash
            - -c
            - >
              apk add openssl envsubst;
              mkdir -p /data/dirk/dirk-{{.}}/certs /data/keystore;
              export INDEX="{{.}}";
              export DIRK_INDEX=$((${HOSTNAME##*-}+1));
              printenv;
              envsubst < /config/dirk.yaml.tml > /data/dirk/dirk-{{.}}/dirk.yaml;
              printenv dirk-ca.crt | base64 -d  > /data/dirk/dirk-{{.}}/certs/ca.crt;
              printenv dirk-ca.key | base64 -d  > /data/dirk/dirk-{{.}}/certs/ca.key;
              bash /scripts/generate_cert.sh /data/dirk/dirk-{{.}}/certs/ ca {{ include "dirk.fullname" $root }}-{{ . }}-0.{{ include "dirk.fullname" $root }};
              chown -R {{ $root.Values.podSecurityContext.runAsUser }}:{{ $root.Values.podSecurityContext.fsGroup }} /data/dirk;
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
        - name: fetch-keys
          image: "{{ $root.Values.cliImage.repository }}:{{ $root.Values.cliImage.tag }}"
          imagePullPolicy: {{ $root.Values.cliImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          args:
          - "sync-dirk-keys"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--wallet-dir"
          - "/data/dirk"
          - "--decryption-key-env"
          - "ESO_DECRYPTION_KEY"
          - "--index"
          - "{{ . }}"
          {{- range $root.Values.dirk.fetchKeysExtraFlags }}
          - {{ . | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: dirk
          image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          securityContext:
            runAsUser: 0
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          args: [ "--base-dir", "/data/dirk/dirk-{{.}}" ]
          ports:
            - name: http
              containerPort: {{ $root.Values.service.httpPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ $root.Values.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
        - name: fetch-keys-syncer
          image: "{{ $root.Values.cliImage.repository }}:{{ $root.Values.cliImage.tag }}"
          imagePullPolicy: {{ $root.Values.cliImage.pullPolicy }}
          securityContext:
            runAsUser: 0
          envFrom:
            - secretRef:
                name: eso-{{ include "common.names.fullname" $root }}
          args:
          - "sync-dirk-keys"
          - "--db-url-env"
          - "ESO_DB_KEYSTORE_URL"
          - "--wallet-dir"
          - "/data/dirk"
          - "--decryption-key-env"
          - "ESO_DECRYPTION_KEY"
          - "--index"
          - "{{ . }}"
          - "--refresh-frequency"
          - "1800"
          {{- range $root.Values.dirk.fetchKeysExtraFlags }}
          - {{ . | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.fullname" $root }}
        - name: scripts
          configMap:
            name: {{ include "common.names.fullname" $root }}-scripts
        - name: data
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi

{{- end }}