# Default values for web3signer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  serviceAccount:
    create: true

  replicaCount: 1

  externalSecrets:
    enabled: false
    secretStoreRef: secretStoreRef
    data:
      - secretKey: MESSAGES_PASSWORD
        remoteRef:
          key: validatorEjectorSecrets
          property: message
      - secretKey: LOGGER_SECRETS
        remoteRef:
          key: validatorEjectorSecrets
          property: loggerSecrets
      - secretKey: ORACLE_ADDRESSES_ALLOWLIST
        remoteRef:
          key: validatorEjectorSecrets
          property: oracleAddressesAllowlist

  initImage:
    repository: "bitnami/kubectl"
    tag: "1.26"
    pullPolicy: IfNotPresent

  image:
    repository: lidofinance/validator-ejector
    pullPolicy: IfNotPresent
    tag: "dev"

  loader:
    repository: nethermindeth/eth-exit-messages
    pullPolicy: IfNotPresent
    tag: "v0.0.15"

loader:
  EIP2335_PASSWORD: "test"
  ENCRYPTION: "EIP2335"
  ENCRYPT_WITH_METADATA: "false"
  BEACON_ENDPOINT: "http://192.168.11.104:5052"
  CUSTODIAN_WEB3SIGNER_MAPPER: '{"custodian1/second": "http://192.168.11.104:9110"}'
  STORAGE_LOCATION: "local/"
  FETCH_INTERVAL: "60"
  SIGNER_MAPPER: '{}'
  LOADER_MAPPER: '{}'
  KEY_LOADER_TYPE: "WEB3SIGNER"
  ENCRYPTION_TYPE: "EIP2335"
  LidoKAPI_OPERATOR_ID: ""
  LidoKAPI_KEYS_PERCENT: "5"

ejector:
  ## Ethereum Consensus Node endpoint
  consensus: "http://localhost:4000"
  ## Ethereum Execution Node endpoint
  execution: "http://localhost:8545"
  ## Address of the Locator contract, can be found in the lido-dao repo
  locatorAddress: "0x12cd349E19Ab2ADBE478Fc538A66C059Cf40CFeC"
  ## Staking Module ID for which operator ID is set
  stakingModuleId: "123"
  ## Operator ID in the Node Operators registry, easiest to get from Operators UI
  operatorId: "123"
  ## Folder to load json exit message files from
  messagesLocation: "messages"
  ## POST validator info to an endpoint instead of sending out an exit message in order to initiate an exit. 
  ## Required if you are using webhook mode
  validatorExitWebhook: ""
  ## Amount of blocks to load events from on start.
  ## Increase if daemon was not running for some time. Defaults to a day of blocks
  blocksPreload: 7200
  ## Amount of blocks to load events from on every poll. Defaults to 1 epoch
  blocksLoop: 32
  ## Time interval in milliseconds to run checks. Defaults to time of 1 epoch
  jobInterval: 384000
  ## Port to serve metrics and health check on
  httpPort: 2122
  ## Enable metrics endpoint
  runMetrics: true
  ## Enable health check endpoint
  runHealthCheck: true
  ## Severity level from which to start showing errors eg info will hide debug messages
  loggerLevel: "info"
  ## Simple or JSON log output: simple/json
  loggerFormat: "simple"
  ## Run the service without actually sending out exit messages
  dryRun: false

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
podSecurityContext: {}

## Whether or not to allocate persistent volume disk for the data directory.
## In case of node failure, the node data directory will still persist.
##
persistence:
  enabled: true
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  annotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

## Configure resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Prometheus Service Monitor
## ref: https://github.com/coreos/prometheus-operator
##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
##
serviceMonitor:
  ## @param metrics.serviceMonitor.enabled Create ServiceMonitor resource(s) for scraping metrics using PrometheusOperator
  ##
  enabled: false
  ## @param metrics.serviceMonitor.namespace The namespace in which the ServiceMonitor will be created
  ##
  namespace: ""
  ## @param metrics.serviceMonitor.interval The interval at which metrics should be scraped
  ##
  interval: 30s
  ## @param metrics.serviceMonitor.scrapeTimeout The timeout after which the scrape is ended
  ##
  scrapeTimeout: ""
  ## @param metrics.serviceMonitor.relabellings Metrics RelabelConfigs to apply to samples before scraping.
  ##
  relabellings: []
  ## @param metrics.serviceMonitor.metricRelabelings Metrics RelabelConfigs to apply to samples before ingestion.
  ##
  metricRelabelings: []
  ## @param metrics.serviceMonitor.honorLabels Specify honorLabels parameter to add the scrape endpoint
  ##
  honorLabels: false
  ## @param metrics.serviceMonitor.additionalLabels Additional labels that can be used so ServiceMonitor resource(s) can be discovered by Prometheus
  ##
  additionalLabels: {}
