{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-{{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: eso-{{ include "common.names.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: ESO_DECRYPTION_KEY_V2
      remoteRef:
        key: {{ include "web3signer.ownership" . }}-external-secrets
        property: decryptionKeyV2
    - secretKey: ESO_DB_KEYSTORE_URL
      remoteRef:
        key: {{ include "web3signer.ownership" . }}-external-secrets
        property: dbKeystoreUrl
    - secretKey: ESO_DB_URL
      remoteRef:
        key: {{ include "web3signer.ownership" . }}-external-secrets
        property: dbUrl
    - secretKey: ESO_DB_USERNAME
      remoteRef:
        key: {{ include "web3signer.ownership" . }}-external-secrets
        property: dbUsername
    - secretKey: ESO_DB_PASSWORD
      remoteRef:
        key: {{ include "web3signer.ownership" . }}-external-secrets
        property: dbPassword
  {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
