{{- if and .Values.deployment.kong.enabled .Values.deployment.nethgate.enabled}}
apiVersion: v1
kind: Service
metadata: 
  name: {{ template "kong.fullname" . }}-nethgate
  namespace:  {{ template "kong.namespace" . }}
  {{- if .Values.deployment.nethgate.svc.annotations }}
  annotations:
  {{- range $key, $value := .Values.deployment.nethgate.svc.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "kong.nethagateMetaLabels" . | nindent 4 }}
spec:
  {{- if .Values.deployment.nethgate.svc.loadBalancerIP }}
  loadBalancerIP: {{ .Values.deployment.nethgate.svc.loadBalancerIP }}
  {{- end }}
  ports:
    - name: nethgate
      protocol: TCP
      port:  {{ .Values.deployment.nethgate.port }}
      targetPort:  {{ .Values.deployment.nethgate.port }}
  selector:
      {{- include "kong.nethagateSelectorLabels" . | nindent 6 }}
  type: {{ .Values.deployment.nethgate.svc.type }}
{{- end -}}