# Basic configuration for Kong without the ingress controller, using the Postgres subchart
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001

namespace: kong-api
image:
  repository: us-east1-docker.pkg.dev/juno-stg-nth/nethgate/saas-api
  tag: "v0.0.1-rc-2"

env:
  prefix: /kong_prefix/
  database: postgres
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

proxy:
  enabled: false

secretVolumes:
- kong-cluster-cert

postgresql:
  enabled: true
  auth:
    username: kong
    database: kong

declarativeSetup:
   enabled: true
   filename: kong.yaml
   
ingressController:
  enabled: false

nodeSelector: 
  node_pool: juno-pool
  network: juno

tolerations:
  - key: "juno-pool"
    operator: "Equal"
    value: "staging"
    effect: "NoSchedule"
  - key: "network"
    operator: "Equal"
    value: "juno"
    effect: "NoSchedule"
