{{- if .Values.ingress.enabled -}}
---
  {{- $baseServiceName := include "common.names.fullname" . -}}
  {{- $routePrefix := .Values.ingress.routePrefix | default "/" -}}
  {{- $defaultPath := list (dict "path" $routePrefix "port" 8000 "pathType" "ImplementationSpecific") -}}
  {{- $paths := .Values.ingress.paths | default $defaultPath -}} 
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . }}
  {{- end }}
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
          {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.serviceName | default $baseServiceName }}
                port:
                  number: {{ $p.port }}
          {{- end }}
    {{- end }}
  {{- else }}
    - http:
        paths:
          {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ $p.pathType }}
            backend:
              service:
                name: {{ $p.serviceName | default $baseServiceName }}
                port:
                  number: {{ $p.port }}
          {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{ tpl (toYaml . | indent 4) . }}
  {{- end }}
{{- end }}
