{{- range $type, $specs := .Values.nodes }}
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "common.names.fullname" $ }}-keystore-cli-{{ $type }}"
  labels:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
spec:
  initContainers:
  - name: keygen
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    command: ["keygen", "-o", "/keys", "-n", "{{ $specs.replicaCount }}"]
    volumeMounts:
    - name: keys
      mountPath: /keys

  containers:
  - name: espresso-keystore-cli
    image: {{ $.Values.keystoreCLI.image.repository }}:{{ $.Values.keystoreCLI.image.tag }}
    imagePullPolicy: {{ $.Values.keystoreCLI.image.pullPolicy }}
    env:
    - name: KEYS_PATH
      value: /keys
    - name: PROJECT_ID
      value: {{ required "Project ID is required" $.Values.keystoreCLI.projectId }}
    - name: SECRET_ID
      value: {{ required "Secret ID is required" $.Values.keystoreCLI.secretId }}-{{ $type }}
    volumeMounts:
    - name: keys
      mountPath: /keys

  volumes:
  - name: keys
    emptyDir: {}

  restartPolicy: Never
{{- end }}
