{{- if .Values.externalSecrets.enabled }}
{{- range $type, $specs := .Values.nodes }}
---
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: "eso-espresso-sequencer-secrets-{{ $type }}"
  {{- with $.Values.global.namespaceOverride }}
  namespace: {{ . }}
  {{- end }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ $.Values.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: "eso-espresso-sequencer-secrets-{{ $type }}"
    creationPolicy: Owner
  {{- with $specs.externalSecrets.data }}
  data:
    {{- . | toYaml | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}