{{- if .Values.externalSecrets.enabled }}
{{- range $type, $specs := .Values.nodes }}
---
apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: "eso-espresso-sequencer-secrets-{{ $type }}"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: gcp-secrets-manager
  target:
    name: "eso-espresso-sequencer-secrets-{{ $type }}"
    creationPolicy: Owner
  {{- if $specs.externalSecrets.data }}
  data:
    {{- $specs.externalSecrets.data | toYaml | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}