{{- range $type, $specs := .Values.nodes }}
---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" $ }}
kind: StatefulSet
metadata:
  name: "{{ include "common.names.fullname" $ }}-{{ $type }}"
spec:
  serviceName: "{{ include "common.names.fullname" $ }}-{{ $type }}"
  replicas: {{ $specs.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6 }}
      type: {{ $type }}
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" $ | nindent 8 }}
        type: {{ $type }}
    spec:
      serviceAccountName: {{ include "common.names.fullname" $ }}
      {{- if $.Values.externalSecrets.enabled }}
      initContainers:
        - name: keygen  # Generates keys for the sequencer
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["keygen", "-o", "/keys", "-n", "{{ $specs.replicaCount }}"]
          volumeMounts:
          - name: keys
            mountPath: /keys
        - name: keystore-cli-pv-keys  # Updates Secret Manager with private keys in the proper format
          image: {{ $.Values.keystoreCLI.image.repository }}:{{ $.Values.keystoreCLI.image.tag }}
          imagePullPolicy: {{ $.Values.keystoreCLI.image.pullPolicy }}
          command: ["pv-keys"]
          env:
          - name: KEYS_PATH
            value: /keys
          - name: PROJECT_ID
            value: {{ required "Project ID is required" $.Values.keystoreCLI.projectId }}
          - name: SECRET_ID
            value: {{ required "Secret ID is required" $.Values.keystoreCLI.pv.secretId }}-{{ $type }}
          volumeMounts:
          - name: keys
            mountPath: /keys
        - name: init-setenv   # Sets keys environment variables for the sequencer
          image: "{{ $.Values.initImage.repository }}:{{ $.Values.initImage.tag }}"
          imagePullPolicy: {{ $.Values.initImage.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              index=$(hostname | grep -o -E "[0-9]+$")
              echo "Detected Pod Index: $index"
              # Ensure environment variables are fetched and then exported with index suffix
              ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=$(echo $ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY_$index)
              ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=$(echo $ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY_$index)
              echo "ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY=${ESPRESSO_SEQUENCER_PRIVATE_STATE_KEY}" >> /etc/espresso/.env
              echo "ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY=${ESPRESSO_SEQUENCER_PRIVATE_STAKING_KEY}" >> /etc/espresso/.env
          envFrom:
            - secretRef:
                name: eso-espresso-sequencer-secrets-{{ $type }}
          volumeMounts:
            - name: init-env
              mountPath: /etc/espresso
        {{- if contains $specs.command "storage-sql" }}
        - name: keystore-cli-db-keys  # Updates Secret Manager with DB credentials in the proper format
          image: {{ $.Values.keystoreCLI.image.repository }}:{{ $.Values.keystoreCLI.image.tag }}
          imagePullPolicy: {{ $.Values.keystoreCLI.image.pullPolicy }}
          command: ["db-keys"]
          env:
          - name: PROJECT_ID
            value: {{ required "Project ID is required" $.Values.keystoreCLI.projectId }}
          - name: SECRET_ID
            value: {{ required "Secret ID is required" $.Values.keystoreCLI.db.secretId }}-{{ $type }}
          - name: SEQUENCER_POSTGRES_HOST
            value: {{ required "DB host is required" $.Values.keystoreCLI.db.host }}
          - name: SEQUENCER_POSTGRES_USER
            value: {{ required "DB user is required" $.Values.keystoreCLI.db.user }}
          volumeMounts:
          - name: keys
            mountPath: /keys
        {{- end }}
      {{- end }}
      containers:
        - name: "sequencer-{{ $type }}"
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            - >
              {{ $specs.command }}
          env:
            {{- range $key, $value := $.Values.nodes_config }}
            - name: {{ $key }}
              value: {{ required (printf "%s is required" $key) $value }}
            {{- end }}
          {{- if $.Values.externalSecrets.enabled }}
            - name: ESPRESSO_SEQUENCER_KEY_FILE
              value: /etc/espresso/.env
          envFrom:
            - secretRef:
                name: eso-espresso-sequencer-secrets-{{ $type }}
          {{- end }}
          ports:
            - name: api
              containerPort: {{ $.Values.nodes_config.ESPRESSO_SEQUENCER_API_PORT }}
          {{- if $specs.volumeMount }}
          volumeMounts:
            - name: consensus-data
              mountPath: {{ $.Values.nodes_config.ESPRESSO_SEQUENCER_STORAGE_PATH }}
          {{- if $.Values.externalSecrets.enabled }}
            - name: private-keys
              mountPath: /etc/espresso
          {{- end }}
          {{- end }}
          {{- with $specs.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
          {{- end }}
      volumes:
        - name: keys
          emptyDir: {}
        - name: init-env
          emptyDir: {}
{{- end }}
