{{- range $type, $specs := .Values.nodes }}
---
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" $ }}
kind: StatefulSet
metadata:
  name: "{{ include "common.names.fullname" $ }}-{{ $type }}"
  {{- if $.Values.global.namespaceOverride }}
  namespace: {{ $.Values.global.namespaceOverride }}
  {{- end }}
spec:
  serviceName: "{{ include "common.names.fullname" $ }}-{{ $type }}"
  replicas: {{ $specs.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" $ | nindent 6 }}
      type: {{ $type }}
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" $ | nindent 8 }}
        type: {{ $type }}
    spec:
      serviceAccountName: {{ include "common.names.fullname" $ }}
      {{- if $.Values.externalSecrets.enabled }}
      initContainers:
        - name: keygen  # Generates keys for the sequencer
          image: {{ include "espresso.build_image_name" (list $.Values.image.repository $.Values.image.tag) }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["keygen", "-o", "/keys", "-n", "{{ $specs.replicaCount }}"]
          volumeMounts:
          - name: keys
            mountPath: /keys
        - name: keystore-cli-pv-keys  # Updates Secret Manager with private keys in the proper format
          image: {{ include "espresso.build_image_name" (list $.Values.keystoreCLI.image.repository $.Values.keystoreCLI.image.tag) }}
          imagePullPolicy: {{ $.Values.keystoreCLI.image.pullPolicy }}
          args: ["pv-keys"]
          env:
          - name: KEYS_PATH
            value: /keys
          - name: PROJECT_ID
            value: {{ (required "Project ID is required" $.Values.keystoreCLI.projectId) | quote }}
          - name: SECRET_ID
            value: {{ required "Secret ID is required" $.Values.keystoreCLI.pv.secretId }}-{{ $type }}
          volumeMounts:
          - name: keys
            mountPath: /keys
        {{- if $specs.sqlStorage }}
        - name: keystore-cli-db-keys  # Updates Secret Manager with DB credentials in the proper format
          image:  {{ include "espresso.build_image_name" (list $.Values.keystoreCLI.image.repository $.Values.keystoreCLI.image.tag) }}
          imagePullPolicy: {{ $.Values.keystoreCLI.image.pullPolicy }}
          args: ["db-keys"]
          env:
          - name: PROJECT_ID
            value: {{ (required "Project ID is required" $.Values.keystoreCLI.projectId) | quote }}
          - name: SECRET_ID
            value: {{ required "Secret ID is required" $.Values.keystoreCLI.db.secretId }}
          - name: SEQUENCER_POSTGRES_HOST
            value: {{ (required "DB host is required" $.Values.keystoreCLI.db.host) | quote }}
          - name: SEQUENCER_POSTGRES_USER
            value: {{ (required "DB user is required" $.Values.keystoreCLI.db.user) | quote }}
          volumeMounts:
          - name: keys
            mountPath: /keys
        {{- end }}
        - name: init-setenv   # Sets keys environment variables for the sequencer
          image: {{ include "espresso.build_image_name" (list $.Values.initImage.repository $.Values.initImage.tag) }}
          imagePullPolicy: {{ $.Values.initImage.pullPolicy }}
          command: ['/bin/sh', '/scripts/init.sh'] 
          envFrom:
            - secretRef:
                name: eso-espresso-sequencer-secrets-{{ $type }}
          volumeMounts:
            - name: init-env
              mountPath: /etc/espresso
            - name: scripts-init
              mountPath: /scripts
      {{- end }}
      containers:
        - name: "sequencer-{{ $type }}"
          image: {{ include "espresso.build_image_name" (list $.Values.image.repository $.Values.image.tag) }} 
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: {{ toYaml $specs.command | nindent 12 }}
          env:
            {{- range $key, $value := $.Values.nodes_config }}
            - name: {{ $key }}
              value: {{ required (printf "%s is required" $key) $value | quote }}
            {{- end }}
          {{- if $.Values.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: sequencer-env-secrets-{{ $type }} 
          {{- end }}
          ports:
            - name: api
              containerPort: {{ $.Values.nodes_config.ESPRESSO_SEQUENCER_API_PORT }}
          {{- if or $specs.volumeMount }}
          volumeMounts:
            - name: consensus-data
              mountPath: {{ $.Values.nodes_config.ESPRESSO_SEQUENCER_STORAGE_PATH }}
          {{- end }}
          {{- with $specs.resources }}
          resources:
            {{ toYaml . | nindent 12 | trim }}
          {{- end }}
        - name: diagnostic-container
          image: ubuntu:20.04
          command: ["sleep", "infinity"]
          envFrom:
            - secretRef:
                name: sequencer-env-secrets-{{ $type }}
          volumeMounts:
            - name: init-env
              mountPath: /etc/espresso
      volumes:
        - name: keys
          emptyDir: {}
        - name: init-env
          emptyDir: {}
        - name: scripts-init
          configMap:
            name: {{ include "common.names.fullname" $ }}-init-{{ $type }}
  volumeClaimTemplates:
    {{- if $specs.volumeMount }}
    - metadata:
        name: consensus-data
        labels:
          {{- include "common.labels.statefulset" $ | nindent 8 }}
      {{- with $.Values.global.persistence.annotations }}
        annotations:
          {{ toYaml . | nindent 10 | trim }}
      {{- end }}
      spec:
        accessModes: {{ $.Values.global.persistence.accessModes }}
        storageClassName: {{ $.Values.global.persistence.storageClassName }}
        resources:
          requests:
            storage: {{ $.Values.global.persistence.size | quote }}
    {{- end }}
{{- end }}
