# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
data:
  root-password: {{ .Values.mysqlRootPassword | b64enc | quote }}
  database: {{ .Values.mysqlDatabase | b64enc | quote }}
  user: {{ .Values.mysqlUser | b64enc | quote }}
  password: {{ .Values.mysqlPassword | b64enc | quote }}
