apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dlcbtc.name" . }}
  namespace:  {{ template "dlcbtc.namespace" . }}
  labels:
    {{- include "dlcbtc.metaLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      {{- include "dlcbtc.matchLabels" . | nindent 6 }}
  serviceName: {{ include "dlcbtc.name" . }}
  template:
    metadata:
      labels:
        {{- include "dlcbtc.matchLabels" . | nindent 8 }}
    spec:
    {{- with (.Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.affinity }}
      affinity:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.global.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
    {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 | trim }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "dlcbtc.name" . }}
      containers:
        - name: dlc-link-attestor
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
          ports:
            {{- range $idx, $Port := .Values.global.service.Ports }}
            - name: {{ $Port.name }}
              containerPort: {{ $Port.port }}
              protocol: {{ $Port.protocol }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/attestor/config.toml
              subPath: config.toml
            {{- if .Values.global.externalSecrets.enabled }}
            - name: external-secrets
              mountPath: /external-secrets
              readOnly: true
            {{- end }}
          env: {{- toYaml .Values.env | nindent 12 }}
          {{- with .Values.global.healthProbe.consensus.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 | trim }}
          {{- end}}
          {{- with .Values.global.healthProbe.consensus.readinessProbe}}
          readinessProbe:
            {{ toYaml . | nindent 12 | trim }}
          {{- end}}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "dlcbtc.name" . }}
      {{- if .Values.global.externalSecrets.enabled }}
        - name: external-secrets
          secret:
            secretName: eso-{{ include "dlcbtc.name" . }}
      {{- end }}