name: Lint Codebase

on: pull_request

jobs:
  build:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Codebase
        uses: super-linter/super-linter@v5.7.2
        env:
          FILTER_REGEX_EXCLUDE: .*(README\.md|Chart\.yaml|NOTES\.txt).*
          VALIDATE_ALL_CODEBASE: false # Only new or modified files will be parsed for validation
          DEFAULT_BRANCH: main
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_JSCPD: false
          VALIDATE_YAML: false
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
