name: 'Prysm Images Rebuild'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Exiting Prysm version to build'
        required: true

jobs:
  build-beacon-chain:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: docker/prysm/
          file: Dockerfile.beacon
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ github.event.inputs.version }}
          tags: nethermindeth/prysm-beacon-chain:${{ github.event.inputs.version }}

  build-validator:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: docker/prysm/
          file: Dockerfile.validator
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: VERSION=${{ github.event.inputs.version }}
          tags: nethermindeth/prysm-validator:${{ github.event.inputs.version }}


